<script lang="ts">
/*******************************************************************************
*                                                                              *
*                           SveltePreview.svelte                              *
*                                                                              *
*******************************************************************************/

  import { onMount, onDestroy } from 'svelte'

  let { code:Code = '', active = false }: { code:string, active:boolean } = $props()

  type CompilationErrorInfo = {
    Type:    'compile'|'runtime';
    Message: string;
    Details: string;
  }

  let PreviewFrame:HTMLIFrameElement
  let CompilationError:CompilationErrorInfo|null = $state(null)
  let compiling:boolean       = $state(false)
  let IFrameURL:string|null   = $state(null)
  let CodeBlobURL:string|null = null    // blob URL for compiled component module
  let SvelteCompiler:typeof import('svelte/compiler')|null = null
  let CompilerLoadFailed = false
  let CompilationGeneration = 0         // incremented on every new compile run

  // Derive the URLs of the two static assets relative to this module's own
  // location.  Using import.meta.url as the base means the paths stay correct
  // regardless of whether the app is served from the domain root, a
  // subdirectory, or even via the file:// protocol.
  const RuntimeURL:string  = new URL('./svelte-runtime.js',  import.meta.url).href
  const CompilerURL:string = new URL('./svelte-compiler.js', import.meta.url).href

/**** loadSvelteCompiler ****/

  async function loadSvelteCompiler ():Promise<typeof import('svelte/compiler')> {
    if (SvelteCompiler != null)    { return SvelteCompiler }
    if (CompilerLoadFailed)        { throw new Error(
      `Compiler not available at ${CompilerURL} — run "npm run build:compiler" and make sure the file is served.`
    ) }
    try {
      const Module = await import(/* @vite-ignore */ CompilerURL) as typeof import('svelte/compiler')
      if (typeof Module.compile !== 'function') {
        throw new Error(
          `Module loaded but compile() not found. Exports: ${Object.keys(Module).join(', ')}`
        )
      }
      SvelteCompiler = Module
      return SvelteCompiler
    } catch (Signal) {
      CompilerLoadFailed = true
      const Reason = (Signal instanceof Error) ? Signal.message : String(Signal)
      throw new Error(`Failed to load Svelte compiler from ${CompilerURL}: ${Reason}`)
    }
  }

/**** compileAndRender ****/

  async function compileAndRender (SvelteCode:string):Promise<void> {
    if (SvelteCode == null) { return }

    const Generation = ++CompilationGeneration
    compiling        = true
    CompilationError = null

    try {
      const Compiler = await loadSvelteCompiler()
      if (Generation !== CompilationGeneration) { return }  // neuere Kompilierung läuft bereits

      const compiled = Compiler.compile(SvelteCode, {
        generate:     'client',
        css:          'external',  // CSS in compiled.css.code, injected into IFrame <style>
        dev:          false,
        experimental: { async:true },
      })

      // Detect Svelte 4 legacy syntax by scanning the source code directly.
      // Strip comments and <style> blocks first to avoid false positives.
      const strippedCode = SvelteCode
        .replace(/<!--[\s\S]*?-->/g,        '')  // HTML comments
        .replace(/<style[\s\S]*?<\/style>/g, '') // <style> blocks
        .replace(/\/\*[\s\S]*?\*\//g,       '')  // /* */ comments
        .replace(/\/\/[^\n]*/g,             '')  // // comments

      const hasLegacyEvents   = /(?:<[^>]+)\son:[a-z]/.test(strippedCode)
      const hasLegacyDispatch = strippedCode.includes('createEventDispatcher')
      const hasStoreSubscript = /\{\s*\$[a-zA-Z_][\w]*\s*[}|]/.test(strippedCode)
      const hasLegacyRuntime  = compiled.js.code.includes('$.push(') &&
                                compiled.js.code.includes('$.init()')

      if (hasLegacyEvents || hasLegacyDispatch || hasStoreSubscript || hasLegacyRuntime) {
        CompilationError = {
          Type:    'compile',
          Message: 'Svelte 4 / legacy syntax detected',
          Details: `
This REPL runs Svelte 5 in runes mode without a bundler.
The compiled output requires legacy runtime support which is not available here.

Known unsupported patterns:
  • on:event  →  use onclick, onfocus, etc.
  • createEventDispatcher  →  use callback props
  • beforeUpdate / afterUpdate  →  use $effect
  • $storeName auto-subscription  →  use $state()
  • Custom Elements in templates

If your code uses none of the above, please report it as a bug.

Svelte 5 migration guide: https://svelte.dev/docs/svelte/v5-migration-guide
`.trim(),
        }
        return  // finally setzt compiling=false
      }

      let processedCode = compiled.js.code
      const CSSCode     = compiled.css?.code ?? ''

    /**** rewrite bare imports generated by the compiler ****/

      // Svelte 5 compiler output contains bare specifiers like 'svelte/client',
      // 'svelte/internal/client', 'zimmerframe' etc. that the browser cannot
      // resolve in a Blob-URL context.
      processedCode = processedCode.replace(
        /^import(\s[^'"]*from)?\s*['"]([^'"]+)['"]\s*;?$/gm,
        (match:string, _from:string, specifier:string) => {
          if (/^(svelte(\/|$)|zimmerframe)/.test(specifier)) {
            return match.replace(/['"][^'"]+['"]/, `'${RuntimeURL}'`)
          }
          return ''
        }
      )

    /**** remove export statements generated by the compiler ****/

      processedCode = processedCode
        .replace(/export\s+default\s+function\s+\w*/g, 'export function Component')
        .replace(/export\s+default\s+class\s+\w*/g,    'export class Component')
        .replace(/export\s+default\s+/g,                'export const Component = ')
        .replace(/export\s*\{[^}]*\}\s*;?/gs,          '')
        .replace(/export\s+(?!(?:function|class|const)\s+Component)/g, '')

    /**** create HTML content for Preview IFrame ****/

      if (IFrameURL   != null) { URL.revokeObjectURL(IFrameURL) }
      if (CodeBlobURL != null) { URL.revokeObjectURL(CodeBlobURL) }

      const CodeBlob    = new Blob([ processedCode ], { type:'text/javascript' })
      CodeBlobURL       = URL.createObjectURL(CodeBlob)
      const HTMLContent = createBlobHTML(CSSCode, CodeBlobURL)
      const HTMLBlob    = new Blob([ HTMLContent ], { type:'text/html' })
      IFrameURL         = URL.createObjectURL(HTMLBlob)
    } catch (Signal) {
      if (Generation === CompilationGeneration) {
        const Err      = Signal as Error & { filename?:string; start?:{ line:number }; frame?:string }
        const FileName = Err.filename || ''
        const Line     = Err.start?.line ?? ''
        const Frame    = Err.frame || ''
        const Details  = (FileName !== '')
          ? `${FileName}:${Line}\n${Frame}`
          : Err.toString()

        CompilationError = {
          Type:    'compile',
          Message: Err.message || 'Kompilierungsfehler',
          Details: Details,
        }
      }
    } finally {
      if (Generation === CompilationGeneration) { compiling = false }
    }
  }

/**** createBlobHTML ****/

  function createBlobHTML (CSSCode:string = '', CodeURL:string):string {
    const BaseStyle = `
*{margin:0;padding:0;box-sizing:border-box;}
html,body{width:100%;height:100%;overflow:hidden;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Oxygen,Ubuntu,Cantarell,sans-serif;}
body{background:white;color:#333;}
#app{width:100%;height:100%;}
`.trim()

    return `<!DOCTYPE html>
<html><head><meta charset="UTF-8">
<style>${BaseStyle}</style>
${CSSCode ? `<style>${CSSCode}</style>` : ''}
</head><body><div id="app"></div>
<script>
// ── Console proxy: forwards all console output to the parent frame ──────────
(function () {
  function serialize (Value) {
    if (Value == null) { return Value }
    if (typeof Value === 'string' || typeof Value === 'number' || typeof Value === 'boolean') return Value;
    if (Value instanceof Error) return { __type: 'Error', message: Value.message, stack: Value.stack };
    try {
      return JSON.parse(JSON.stringify(Value, function (_key, v) {
        if (typeof v === 'bigint')   return { __type: 'BigInt',   Value: String(v) };
        if (typeof v === 'function') return { __type: 'Function', Value: v.name || '(anonymous)' };
        if (v instanceof Error)      return { __type: 'Error',    Message: v.message, stack: v.stack };
        return v;
      }));
    } catch (_) {
      return String(Value);
    }
  }

  var _console = {
    log:   console.log.bind(console),
    warn:  console.warn.bind(console),
    error: console.error.bind(console),
    info:  console.info.bind(console),
    dir:   console.dir.bind(console),
    clear: console.clear.bind(console),
  };

  ['log','warn','error','info','dir'].forEach(function (Level) {
    console[Level] = function () {
      var ArgList = Array.prototype.slice.call(arguments).map(serialize);
      window.parent.postMessage({ type: 'console-' + Level, args:ArgList }, '*');
      _console[Level].apply(console, arguments);
    };
  });

  console.clear = function () {
    window.parent.postMessage({ type: 'console-clear' }, '*');
    _console.clear();
  };
})();
<\/script>
<script type="module">
window.addEventListener('error', (Event) => {
  window.parent.postMessage({ type: 'runtime-error', message: Event.message, error: Event.error ? Event.error.stack : Event.message }, '*');
  Event.preventDefault();
});
window.addEventListener('unhandledrejection', (Event) => {
  window.parent.postMessage({ type: 'runtime-error', message: 'Promise: ' + Event.reason, error: Event.reason ? Event.reason.toString() : '' }, '*');
  Event.preventDefault();
});
import { mount, enable_async_mode_flag } from '${RuntimeURL}';
enable_async_mode_flag();
import { Component } from '${CodeURL}';
try {
  const Target = document.getElementById('app');
  mount(Component, { target:Target });
  window.parent.postMessage({ type:'success' }, '*');
} catch (err) {
  window.parent.postMessage({ type:'runtime-error', message:err.message, error:err.stack || err.toString() }, '*');
  console.error(err);
}
<\/script></body></html>`
  }

/**** handleMessage ****/

  function handleMessage (Event:MessageEvent):void {
    if (Event.data?.type === 'runtime-error') {
      CompilationError = {
        Type:    'runtime',
        Message: Event.data.message || 'Runtime Error',
        Details: Event.data.error  || '',
      }
    } else if (Event.data?.type === 'success') {
      CompilationError = null
    }
  }

/**** onMount ****/

  onMount(() => {
    window.addEventListener('message', handleMessage)
    loadSvelteCompiler()  // warm up — load compiler before first keystroke
  })

/**** onDestroy ****/

  onDestroy(() => {
    window.removeEventListener('message', handleMessage)
    if (IFrameURL   != null) { URL.revokeObjectURL(IFrameURL) }
    if (CodeBlobURL != null) { URL.revokeObjectURL(CodeBlobURL) }
  })

  let lastCompiledCode = ''

  $effect(() => {
    // Only compile when Preview tab becomes active AND code has changed
    if (active && (Code !== lastCompiledCode)) {
      lastCompiledCode = Code
      CompilationError = null
      compileAndRender(Code)
    }
  })
</script>

<div class="preview-container">
  {#if CompilationError}
    <div
      class="error-message"
      class:compile-error={CompilationError.Type === 'compile'}
      class:runtime-error={CompilationError.Type === 'runtime'}
    >
      <h3>{CompilationError.Type === 'compile' ? '⚠️ Compile Error' : '❌ Runtime Error'}</h3>
      <p>{CompilationError.Message}</p>
      {#if CompilationError.Details}<pre>{CompilationError.Details}</pre>{/if}
    </div>
  {:else if compiling}
    <div class="loading"><div class="spinner"></div><p>Kompiliere…</p></div>
  {/if}
  <iframe
    bind:this={PreviewFrame}
    class="preview-frame"
    class:has-error={CompilationError}
    title="Preview"
    src={IFrameURL || 'about:blank'}
  ></iframe>
</div>

<style>
  .preview-container { width:100%; height:100%; position:relative; background:white; }
  .preview-frame     { width:100%; height:100%; border:none; background:white; }
  .preview-frame.has-error { opacity:0.3; }

  .error-message {
    position:absolute; top:20px; left:20px; right:20px;
    background:white; border-radius:8px; padding:20px;
    box-shadow:0 4px 12px rgba(0,0,0,0.15); z-index:10;
    max-height:80%; overflow:auto;
  }
  .error-message.compile-error { border-left:4px solid #ff9800; }
  .error-message.runtime-error { border-left:4px solid #f44336; }
  .error-message h3  { margin:0 0 10px; font-size:18px; }
  .error-message p   { margin:0 0 10px; color:#666; }
  .error-message pre {
    background:#f5f5f5; padding:10px; border-radius:4px;
    overflow-x:auto; font-size:12px; color:#333;
    white-space:pre-wrap; word-wrap:break-word;
  }

  .loading {
    position:absolute; top:50%; left:50%;
    transform:translate(-50%,-50%); text-align:center; z-index:5;
  }
  .spinner {
    border:3px solid #f3f3f3; border-top:3px solid #ff3e00;
    border-radius:50%; width:40px; height:40px;
    animation:spin 1s linear infinite; margin:0 auto 10px;
  }
  @keyframes spin { 0%{transform:rotate(0deg)} 100%{transform:rotate(360deg)} }
  .loading p { color:#666; font-size:14px; }
</style>
