<script>
  import { onMount, onDestroy } from 'svelte';
  
  export let Code = '';
  
  let PreviewFrame;
  let CompilationError = null;
  let compiling        = false;
  let IFrameURL        = '';
  let SvelteCompiler   = null;
  
/**** loadSvelteCompiler ****/

  async function loadSvelteCompiler () {
    if (SvelteCompiler) return SvelteCompiler;
    try {
      const Module = await import('svelte/compiler');
      SvelteCompiler = Module;
      return SvelteCompiler;
    } catch (Signal) {
      throw Signal;
    }
  }
    
/**** compileAndRender ****/

  async function compileAndRender (SvelteCode) {
    if (SvelteCode == null) { return }
    
    compiling        = true;
    CompilationError = null;
    
    try {
      const Compiler = await loadSvelteCompiler();
      const compiled = Compiler.compile(SvelteCode, {
        generate: 'dom',
        hydratable: false,
        css: 'external',
        dev: true
      });
      
      let processedCode = compiled.js.code;
      let CSSCode       = (compiled.css?.code != null ? compiled.css.code : '');
      
    /**** remove import statements generated by the compiler ****/

      processedCode = processedCode.replace(/import\s*\{[^}]*\}\s*from\s*['"][^'"]+['"]\s*;?/gs, '');
      processedCode = processedCode.replace(/import\s*\*\s*as\s*\w+\s*from\s*['"][^'"]+['"]\s*;?/gs, '');
      processedCode = processedCode.replace(/import\s*['"][^'"]+['"]\s*;?/gs, '');
      processedCode = processedCode.replace(/import\s+\w+\s*from\s*['"][^'"]+['"]\s*;?/gs, '');
      
    /**** remove export statements generated by the compiler ****/

      processedCode = processedCode.replace(/export\s*\{[^}]*\}\s*;?/gs, '');
      processedCode = processedCode.replace(/export\s+default\s+/g, 'window.Component = ');
      processedCode = processedCode.replace(/export\s+/g, '');
      
    /**** create HTML content for Preview IFrame ****/

      const HTMLContent = createBlobHTML(processedCode, CSSCode);
      const HTMLBlob    = new Blob([HTMLContent], { type:'text/html' });
      
      if (IFrameURL != null) {
        URL.revokeObjectURL(IFrameURL);
      }
      
      IFrameURL = URL.createObjectURL(HTMLBlob);
    } catch (Signal) {
      const FileName = Signal.filename || '';
      const Line     = Signal.start?.line || '';
      const Frame    = Signal.frame || '';
      const Details  = (FileName != null ? FileName + ':' + Line + '\n' + Frame : Signal.toString());
      
      CompilationError = {
        type: 'compile',
        message: Signal.message || 'Kompilierungsfehler',
        details: Details
      };
    } finally {
      compiling = false;
    }
  }
  
/**** createBlobHTML ****/

  function createBlobHTML (compiledCode, CSSCode = '') {
    const Parts = [];
      Parts.push('<!DOCTYPE html><html><head><meta charset="UTF-8">');
      Parts.push('<style>*{margin:0;padding:0;box-sizing:border-box;}html,body{width:100%;height:100%;overflow:hidden;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Oxygen,Ubuntu,Cantarell,sans-serif;}body{margin:0;padding:16px;background:white;color:#333;}#app{width:100%;height:100%;}</style>');
      if (CSSCode != null) {
        Parts.push('<style>' + CSSCode + '</style>');
      }
      Parts.push('</head><body><div id="app"></div>');
      Parts.push('<script>');
    
    /**** Svelte runtime ****/

      Parts.push('const globals=(typeof window!=="undefined"?window:typeof global!=="undefined"?global:typeof globalThis!=="undefined"?globalThis:{});');
      Parts.push('function noop(){}');
      Parts.push('function run(fn){return fn()}');
      Parts.push('function blank_object(){return Object.create(null)}');
      Parts.push('function run_all(fns){fns.forEach(run)}');
      Parts.push('function is_function(thing){return typeof thing==="function"}');
      Parts.push('function safe_not_equal(a,b){return a!=a?b==b:a!==b||((a&&typeof a==="object")||typeof a==="function")}');
      Parts.push('function append_dev(target,node){target.appendChild(node)}');
      Parts.push('function append(target,node){target.appendChild(node)}');
      Parts.push('function insert_dev(target,node,anchor){target.insertBefore(node,anchor||null)}');
      Parts.push('function insert(target,node,anchor){target.insertBefore(node,anchor||null)}');
      Parts.push('function detach_dev(node){if(node.parentNode)node.parentNode.removeChild(node)}');
      Parts.push('function detach(node){if(node.parentNode)node.parentNode.removeChild(node)}');
      Parts.push('function destroy_each(iterations,detaching){for(let i=0;i<iterations.length;i+=1){if(iterations[i])iterations[i].d(detaching)}}');
      Parts.push('function ensure_array_like(array_like_or_iterator){return array_like_or_iterator?.length!==undefined?array_like_or_iterator:Array.from(array_like_or_iterator)}');
      Parts.push('function ensure_array_like_dev(array_like_or_iterator){return ensure_array_like(array_like_or_iterator)}');
      Parts.push('function outro_and_destroy_block(block,lookup){transition_out(block,1,1,()=>{lookup.delete(block.key)});return block}');
      Parts.push('function fix_and_destroy_block(block,lookup){block.d(1);lookup.delete(block.key)}');
      Parts.push('function update_keyed_each(old_blocks,dirty,get_key,dynamic,ctx,list,lookup,node,destroy,create_each_block,next,get_context){let o=old_blocks.length;let n=list.length;let i=o;const old_indexes={};while(i--)old_indexes[old_blocks[i].key]=i;const new_blocks=[];const new_lookup=new Map();const deltas=new Map();const updates=[];i=n;while(i--){const child_ctx=get_context(ctx,list,i);const key=get_key(child_ctx);let block=lookup.get(key);if(!block){block=create_each_block(key,child_ctx);block.c()}else if(dynamic){updates.push(()=>block.p(child_ctx,dirty))}new_lookup.set(key,new_blocks[i]=block);if(key in old_indexes)deltas.set(key,Math.abs(i-old_indexes[key]))}const will_move=new Set();const did_move=new Set();function insert(block){transition_in(block,1);block.m(node,next);lookup.set(block.key,block);next=block.first;n--}while(o&&n){const new_block=new_blocks[n-1];const old_block=old_blocks[o-1];const new_key=new_block.key;const old_key=old_block.key;if(new_block===old_block){next=new_block.first;o--;n--}else if(!new_lookup.has(old_key)){destroy(old_block,lookup);o--}else if(!lookup.has(new_key)||will_move.has(new_key)){insert(new_block)}else if(did_move.has(old_key)){o--}else if(deltas.get(new_key)>deltas.get(old_key)){did_move.add(new_key);insert(new_block)}else{will_move.add(old_key);o--}}while(o--){const old_block=old_blocks[o];if(!new_lookup.has(old_block.key))destroy(old_block,lookup)}while(n)insert(new_blocks[n-1]);run_all(updates);return new_blocks}');
      Parts.push('function validate_each_keys(ctx,list,get_context,get_key){const keys=new Set();for(let i=0;i<list.length;i++){const key=get_key(get_context(ctx,list,i));if(keys.has(key)){throw new Error("Cannot have duplicate keys in a keyed each")}keys.add(key)}}');
      Parts.push('function validate_each_argument(arg){if(typeof arg!=="string"&&!(arg&&typeof arg==="object"&&"length"in arg)&&!(typeof arg==="object"&&Symbol.iterator in arg)){throw new Error("{#each} only works with iterable values like arrays, iterators, and strings")}}');
      Parts.push('function element(name){return document.createElement(name)}');
      Parts.push('function element_is(name,is){return document.createElement(name,{is})}');
      Parts.push('function object_without_properties(obj,exclude){const target={};for(const k in obj){if(Object.prototype.hasOwnProperty.call(obj,k)&&exclude.indexOf(k)===-1)target[k]=obj[k]}return target}');
      Parts.push('function text(data){return document.createTextNode(data)}');
      Parts.push('function space(){return text(" ")}');
      Parts.push('function empty(){return text("")}');
      Parts.push('function listen_dev(node,event,handler,options,has_prevent_default,has_stop_propagation,has_stop_immediate_propagation){node.addEventListener(event,handler,options);return()=>node.removeEventListener(event,handler,options)}');
      Parts.push('function listen(node,event,handler,options){node.addEventListener(event,handler,options);return()=>node.removeEventListener(event,handler,options)}');
      Parts.push('function attr_dev(node,attribute,value){attr(node,attribute,value)}');
      Parts.push('function attr(node,attribute,value){if(value==null)node.removeAttribute(attribute);else if(node.getAttribute(attribute)!==value)node.setAttribute(attribute,value)}');
      Parts.push('function children(element){return Array.from(element.childNodes)}');
      Parts.push('function claim_element(nodes,name,attributes,svg){for(let i=0;i<nodes.length;i+=1){const node=nodes[i];if(node.nodeName===name){let j=0;const remove=[];while(j<node.attributes.length){const attribute=node.attributes[j++];if(!attributes[attribute.name]){remove.push(attribute.name)}}remove.forEach(v=>node.removeAttribute(v));return nodes.splice(i,1)[0]}}return svg?svg_element(name):element(name)}');
      Parts.push('function claim_text(nodes,data){for(let i=0;i<nodes.length;i+=1){const node=nodes[i];if(node.nodeType===3){node.data=""+data;return nodes.splice(i,1)[0]}}return text(data)}');
      Parts.push('function claim_space(nodes){return claim_text(nodes," ")}');
      Parts.push('function set_input_value_dev(input,value){set_input_value(input,value)}');
      Parts.push('function query_selector_all(selector,parent=document.body){return Array.from(parent.querySelectorAll(selector))}');
      Parts.push('function contenteditable_truthy_values(){return["true",""]}');
      Parts.push('function set_data_dev(text,data){set_data(text,data)}');
      Parts.push('function set_data(text,data){data=""+data;if(text.data===data)return;text.data=data}');
      Parts.push('function set_input_value(input,value){input.value=value==null?"":value}');
      Parts.push('function set_input_type(input,type){try{input.type=type}catch(e){}}');
      Parts.push('function select_option(select,value,mounting){for(let i=0;i<select.options.length;i+=1){const option=select.options[i];const option_value=option.__value!==undefined?option.__value:option.value;if(option_value===value){option.selected=true;return}}if(!mounting||value!==undefined){select.selectedIndex=-1}}');
      Parts.push('function select_options(select,value){for(let i=0;i<select.options.length;i+=1){const option=select.options[i];const option_value=option.__value!==undefined?option.__value:option.value;option.selected=~value.indexOf(option_value)}}');
      Parts.push('function select_value(select){const selected_option=select.querySelector(":checked")||select.options[0];return selected_option&&(selected_option.__value!==undefined?selected_option.__value:selected_option.value)}');
      Parts.push('function select_multiple_value(select){return[].map.call(select.querySelectorAll(":checked"),option=>option.__value!==undefined?option.__value:option.value)}');
      Parts.push('function add_resize_listener(node,fn){return noop}');
      Parts.push('function is_crossorigin(){return true}');
      Parts.push('function timeRangesToArray(ranges){const array=[];for(let i=0;i<ranges.length;i+=1){array.push({start:ranges.start(i),end:ranges.end(i)})}return array}');
      Parts.push('function set_style(node,key,value,important){if(value==null)node.style.removeProperty(key);else node.style.setProperty(key,value,important?"important":"")}');
      Parts.push('function toggle_class(element,name,toggle){element.classList[toggle?"add":"remove"](name)}');
      Parts.push('function prop_dev(node,property,value){node[property]=value;return node}');
      Parts.push('function set_attributes(element,attributes){const descriptors=Object.getOwnPropertyDescriptors(element.__proto__);for(const key in attributes){if(attributes[key]==null){element.removeAttribute(key)}else if(key==="style"){element.style.cssText=attributes[key]}else if(key==="__value"){element.value=element[key]=attributes[key]}else if(descriptors[key]&&descriptors[key].set&&(key==="className"||key==="innerHTML"||key==="textContent"||key==="innerText")){element[key]=attributes[key]}else{attr(element,key,attributes[key])}}}');
      Parts.push('function set_svg_attributes(element,attributes){for(const key in attributes){attr(element,key,attributes[key])}}');
      Parts.push('function set_custom_element_data(node,prop,value){if(prop in node){node[prop]=typeof node[prop]==="boolean"&&value===""?true:value}else{attr(node,prop,value)}}');
      Parts.push('function set_custom_element_data_map(node,data_map){Object.keys(data_map).forEach((key)=>{set_custom_element_data(node,key,data_map[key])})}');
      Parts.push('function construct_svelte_component(component,props){return new component(props)}');
      Parts.push('function svg_element(name){return document.createElementNS("http://www.w3.org/2000/svg",name)}');
      Parts.push('function xlink_attr(node,attribute,value){node.setAttributeNS("http://www.w3.org/1999/xlink",attribute,value)}');
      Parts.push('function get_binding_group_value(group,__value,checked){const value=new Set();for(let i=0;i<group.length;i+=1){if(group[i].checked)value.add(group[i].__value)}if(!checked)value.delete(__value);return Array.from(value)}');
      Parts.push('function to_number(value){return value===""?null:+value}');
      Parts.push('function time_ranges_to_array(ranges){const array=[];for(let i=0;i<ranges.length;i+=1){array.push({start:ranges.start(i),end:ranges.end(i)})}return array}');
      Parts.push('function action_destroyer(action_result){return action_result&&is_function(action_result.destroy)?action_result.destroy:noop}');
      Parts.push('function custom_event(type,detail,{bubbles=false,cancelable=false}={}){const e=document.createEvent("CustomEvent");e.initCustomEvent(type,bubbles,cancelable,detail);return e}');
      Parts.push('function validate_slots(name,slot,keys){}');
      Parts.push('function add_location(element,file,line,column,char){}');
      Parts.push('function dispatch_dev(type,detail){document.dispatchEvent(custom_event(type,Object.assign({version:"4.2.20"},detail),{bubbles:true}))}');
      Parts.push('function append_styles(target,style_sheet_id,styles){}');
    
      Parts.push('let current_component;');
      Parts.push('function set_current_component(component){current_component=component}');
      Parts.push('function get_current_component(){if(!current_component)throw new Error("Function called outside component");return current_component}');
      Parts.push('function onMount(fn){get_current_component().$$.on_mount.push(fn)}');
      Parts.push('function onDestroy(fn){get_current_component().$$.on_destroy.push(fn)}');
      Parts.push('function createEventDispatcher(){const component=get_current_component();return(type,detail,{cancelable=false}={})=>{const callbacks=component.$$.callbacks[type];if(callbacks){const event=custom_event(type,detail,{cancelable});callbacks.slice().forEach(fn=>{fn.call(component,event)});return!event.defaultPrevented}return true}}');
      Parts.push('function beforeUpdate(fn){get_current_component().$$.before_update.push(fn)}');
      Parts.push('function afterUpdate(fn){get_current_component().$$.after_update.push(fn)}');
      Parts.push('function setContext(key,context){get_current_component().$$.context.set(key,context);return context}');
      Parts.push('function getContext(key){return get_current_component().$$.context.get(key)}');
      Parts.push('function hasContext(key){return get_current_component().$$.context.has(key)}');
      Parts.push('function getAllContexts(){return get_current_component().$$.context}');
      Parts.push('const promise_counter=new WeakMap();');
      Parts.push('function tick(){return resolved_promise}');
    
    /**** Svelte stores ****/

      Parts.push('const subscriber_queue=[];');
      Parts.push('function is_store(obj){return obj!=null&&typeof obj.subscribe==="function"}');
      Parts.push('function validate_store(store,name){if(store!=null&&typeof store.subscribe!=="function"){throw new Error("`"+name+"` is not a store with a `subscribe` method")}}');
      Parts.push('function component_subscribe(component,store,callback){const unsub=store.subscribe(callback);component.$$.on_destroy.push(unsub);return callback}');
      Parts.push('function writable(value,start){let stop;const subscribers=new Set();function set(new_value){if(safe_not_equal(value,new_value)){value=new_value;if(stop){const run_queue=!subscriber_queue.length;for(const subscriber of subscribers){subscriber[1]();subscriber_queue.push(subscriber,value)}if(run_queue){for(let i=0;i<subscriber_queue.length;i+=2){subscriber_queue[i][0](subscriber_queue[i+1])}subscriber_queue.length=0}}else{subscribers.forEach(sub=>sub[0](value))}}}function update(fn){set(fn(value))}function subscribe(run,invalidate=noop){const subscriber=[run,invalidate];subscribers.add(subscriber);if(subscribers.size===1){stop=start?start(set):null}run(value);return()=>{subscribers.delete(subscriber);if(subscribers.size===0&&stop){stop();stop=null}}}return{set,update,subscribe}}');
      Parts.push('function readable(value,start){return{subscribe:writable(value,start).subscribe}}');
      Parts.push('function derived(stores,fn,initial_value){const single=!Array.isArray(stores);const stores_array=single?[stores]:stores;const auto=fn.length<2;return readable(initial_value,(set)=>{let started=false;const values=[];let pending=0;let cleanup=noop;const sync=()=>{if(pending)return;cleanup();const result=fn(single?values[0]:values,set);if(auto)set(result);else cleanup=is_function(result)?result:noop};const unsubscribers=stores_array.map((store,i)=>store.subscribe((value)=>{values[i]=value;pending&=~(1<<i);if(started)sync()},(()=>{pending|=1<<i})));started=true;sync();return function stop(){run_all(unsubscribers);cleanup()}})}');
      Parts.push('function set_store_value(store,ret,value){store.set(value);return ret}');
      Parts.push('function get(store){let value;store.subscribe(v=>value=v)();return value}');
    
      Parts.push('const dirty_components=[];');
      Parts.push('const binding_callbacks=[];');
      Parts.push('let render_callbacks=[];');
      Parts.push('const flush_callbacks=[];');
      Parts.push('const resolved_promise=Promise.resolve();');
      Parts.push('let update_scheduled=false;');
      
      Parts.push('function schedule_update(){if(!update_scheduled){update_scheduled=true;resolved_promise.then(flush)}}');
      Parts.push('function add_render_callback(fn){render_callbacks.push(fn)}');
      Parts.push('const seen_callbacks=new Set();');
      Parts.push('let flushidx=0;');
      
      Parts.push('function flush(){if(flushidx!==0)return;const saved_component=current_component;do{try{while(flushidx<dirty_components.length){const component=dirty_components[flushidx];flushidx++;set_current_component(component);update(component.$$)}}catch(e){dirty_components.length=0;flushidx=0;throw e}set_current_component(null);dirty_components.length=0;flushidx=0;while(binding_callbacks.length)binding_callbacks.pop()();for(let i=0;i<render_callbacks.length;i+=1){const callback=render_callbacks[i];if(!seen_callbacks.has(callback)){seen_callbacks.add(callback);callback()}}render_callbacks.length=0}while(dirty_components.length);while(flush_callbacks.length)flush_callbacks.pop()();update_scheduled=false;seen_callbacks.clear();set_current_component(saved_component)}');
      
      Parts.push('function update($$){if($$.fragment!==null){$$.update();run_all($$.before_update);const dirty=$$.dirty;$$.dirty=[-1];$$.fragment&&$$.fragment.p($$.ctx,dirty);$$.after_update.forEach(add_render_callback)}}');
      
      Parts.push('const outroing=new Set();');
      Parts.push('let outros;');
      Parts.push('function group_outros(){outros={r:0,c:[],p:outros}}');
      Parts.push('function check_outros(){if(!outros.r)run_all(outros.c);outros=outros.p}');
      Parts.push('function handle_promise(promise,info){const token=info.token={};function update(type,index,key,value){if(info.token!==token)return;info.resolved=value;let child_ctx=info.ctx;if(key!==undefined){child_ctx=child_ctx.slice();child_ctx[key]=value}const block=type&&(info.current=type)(child_ctx);let needs_flush=false;if(info.block){if(info.blocks){info.blocks.forEach((block,i)=>{if(i!==index&&block){group_outros();transition_out(block,1,1,()=>{if(info.blocks[i]===block){info.blocks[i]=null}});check_outros()}});needs_flush=true}else{info.block.d(1)}block.c();transition_in(block,1);block.m(info.mount(),info.anchor);if(needs_flush)flush()}info.block=block;if(info.blocks)info.blocks[index]=block}if(is_promise(promise)){const current_component=get_current_component();promise.then(value=>{set_current_component(current_component);update(info.then,1,info.value,value);set_current_component(null)},error=>{set_current_component(current_component);update(info.catch,2,info.error,error);set_current_component(null);if(!info.hasCatch){throw error}});if(info.current!==info.pending){update(info.pending,0);return true}}else{if(info.current!==info.then){update(info.then,1,info.value,promise);return true}info.resolved=promise}}');
      Parts.push('function is_promise(value){return!!value&&(typeof value==="object"||typeof value==="function")&&typeof value.then==="function"}');
      Parts.push('function update_await_block_branch(info,ctx,dirty){const child_ctx=ctx.slice();const{resolved}=info;if(info.current===info.then){child_ctx[info.value]=resolved}if(info.current===info.catch){child_ctx[info.error]=resolved}info.block.p(child_ctx,dirty)}');
      Parts.push('function transition_in(block,local){if(block&&block.i){outroing.delete(block);block.i(local)}}');
      Parts.push('function transition_out(block,local,detach,callback){if(block&&block.o){if(outroing.has(block))return;outroing.add(block);outros.c.push(()=>{outroing.delete(block);if(callback){if(detach)block.d(1);callback()}});block.o(local)}else if(callback)callback()}');
      
      Parts.push('function mount_component(component,target,anchor){const{fragment,after_update}=component.$$;fragment&&fragment.m(target,anchor);add_render_callback(()=>{const new_on_destroy=component.$$.on_mount.map(run).filter(is_function);if(component.$$.on_destroy)component.$$.on_destroy.push(...new_on_destroy);else run_all(new_on_destroy);component.$$.on_mount=[]});after_update.forEach(add_render_callback)}');
    
      Parts.push('function destroy_component(component,detaching){const $$=component.$$;if($$.fragment!==null){run_all($$.on_destroy);$$.fragment&&$$.fragment.d(detaching);$$.on_destroy=$$.fragment=null;$$.ctx=[]}}');
      
      Parts.push('function make_dirty(component,i){if(component.$$.dirty[0]===-1){dirty_components.push(component);schedule_update();component.$$.dirty.fill(0)}component.$$.dirty[(i/31)|0]|=(1<<(i%31))}');
      
      Parts.push('function init(component,options,instance,create_fragment,not_equal,props,append_styles,dirty=[-1]){const parent_component=current_component;set_current_component(component);const $$=component.$$={fragment:null,ctx:[],props,update:noop,not_equal,bound:blank_object(),on_mount:[],on_destroy:[],on_disconnect:[],before_update:[],after_update:[],context:new Map(options.context||(parent_component?parent_component.$$.context:[])),callbacks:blank_object(),dirty,skip_bound:false,root:options.target||parent_component.$$.root};append_styles&&append_styles($$.root);let ready=false;$$.ctx=instance?instance(component,options.props||{},(i,ret,...rest)=>{const value=rest.length?rest[0]:ret;if($$.ctx&&not_equal($$.ctx[i],$$.ctx[i]=value)){if(!$$.skip_bound&&$$.bound[i])$$.bound[i](value);if(ready)make_dirty(component,i)}return ret}):[];$$.update();ready=true;run_all($$.before_update);$$.fragment=create_fragment?create_fragment($$.ctx):false;if(options.target){if(options.hydrate){const nodes=children(options.target);$$.fragment&&$$.fragment.l(nodes);nodes.forEach(detach)}else{$$.fragment&&$$.fragment.c()}if(options.intro)transition_in(component.$$.fragment);mount_component(component,options.target,options.anchor);flush()}set_current_component(parent_component)}');
      
      Parts.push('class SvelteComponent{$destroy(){destroy_component(this,1);this.$destroy=noop}$on(type,callback){if(!is_function(callback))return noop;const callbacks=(this.$$.callbacks[type]||(this.$$.callbacks[type]=[]));callbacks.push(callback);return()=>{const index=callbacks.indexOf(callback);if(index!==-1)callbacks.splice(index,1)}}$set($$props){if(this.$$set&&Object.keys($$props).length){this.$$.skip_bound=true;this.$$set($$props);this.$$.skip_bound=false}}}');
      
      Parts.push('class SvelteComponentDev extends SvelteComponent{constructor(options){if(!options||(!options.target&&!options.$$inline)){throw new Error("\'target\' is a required option")}super()}$destroy(){super.$destroy();this.$destroy=()=>{console.warn("Component was already destroyed")}}$capture_state(){}$inject_state(){}}');
      
      Parts.push('window.addEventListener("error",(e)=>{window.parent.postMessage({type:"runtime-error",message:e.message,error:e.error?e.error.stack:e.message},"*");e.preventDefault()});');
      Parts.push('window.addEventListener("unhandledrejection",(e)=>{window.parent.postMessage({type:"runtime-error",message:"Promise:"+e.reason,error:e.reason?e.reason.toString():""},"*");e.preventDefault()});');
      
      Parts.push('try{');
      Parts.push(compiledCode);
      Parts.push('new window.Component({target:document.getElementById("app")});');
      Parts.push('window.parent.postMessage({type:"success"},"*");');
      Parts.push('}catch(err){window.parent.postMessage({type:"runtime-error",message:err.message,error:err.stack||err.toString()},"*");console.error(err)}');
      Parts.push('</' + 'script></body></html>');
    return Parts.join('');
  }
  
/**** handleMessage ****/

  function handleMessage (Event) {
    if (Event.data?.type === 'runtime-error') {
      CompilationError = {
        type: 'runtime',
        message: Event.data.message || 'Runtime Error',
        details: Event.data.error || ''
      };
    } else if (Event.data?.type === 'success') {
      CompilationError = null;
    }
  }
    
/**** onMount ****/

  onMount(() => {
    window.addEventListener('message', handleMessage);
    loadSvelteCompiler();
  });
      
/**** onDestroy ****/

  onDestroy(() => {
    window.removeEventListener('message', handleMessage);
    if (IFrameURL != null) { URL.revokeObjectURL(IFrameURL) }
  });
  
  let TimeoutId;
  $: {
    if (Code != null) {
      clearTimeout(TimeoutId);
      CompilationError = null;
      TimeoutId = setTimeout(() => compileAndRender(Code), 500);
    }
  }
</script>

<div class="preview-container">
  {#if CompilationError}
    <div class="error-message" class:compile-error={CompilationError.type==='compile'} class:runtime-error={CompilationError.type==='runtime'}>
      <h3>{CompilationError.type==='compile'?'⚠️ Compile Error':'❌ Runtime Error'}</h3>
      <p>{CompilationError.message}</p>
      {#if CompilationError.details}<pre>{CompilationError.details}</pre>{/if}
    </div>
  {:else if compiling}
    <div class="loading"><div class="spinner"></div><p>Kompiliere...</p></div>
  {/if}
  <iframe bind:this={PreviewFrame} class="preview-frame" class:has-error={CompilationError} title="Preview" src={IFrameURL}></iframe>
</div>

<style>
  .preview-container{width:100%;height:100%;position:relative;background:white}
  .preview-frame{width:100%;height:100%;border:none;background:white}
  .preview-frame.has-error{opacity:0.3}
  .error-message{position:absolute;top:20px;left:20px;right:20px;background:white;border-radius:8px;padding:20px;box-shadow:0 4px 12px rgba(0,0,0,0.15);z-index:10;max-height:80%;overflow:auto}
  .error-message.compile-error{border-left:4px solid #ff9800}
  .error-message.runtime-error{border-left:4px solid #f44336}
  .error-message h3{margin:0 0 10px 0;font-size:18px}
  .error-message p{margin:0 0 10px 0;color:#666}
  .error-message pre{background:#f5f5f5;padding:10px;border-radius:4px;overflow-x:auto;font-size:12px;color:#333;white-space:pre-wrap;word-wrap:break-word}
  .loading{position:absolute;top:50%;left:50%;transform:translate(-50%,-50%);text-align:center;z-index:5}
  .spinner{border:3px solid #f3f3f3;border-top:3px solid #ff3e00;border-radius:50%;width:40px;height:40px;animation:spin 1s linear infinite;margin:0 auto 10px}
  @keyframes spin{0%{transform:rotate(0deg)}100%{transform:rotate(360deg)}}
  .loading p{color:#666;font-size:14px}
</style>
